apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-carrier-allchannel
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-carrier-allchannel
  chart:
    git: https://github.com/ayhamkassab/blockchain-automation-framework.git
    ref: master
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      network:
        version 2.2.0
      images:
        fabrictools: hyperledger/fabric-tools:2.2.0
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://172.16.0.6:30000
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer0.supplychain-net:7050
    channeltx: |-
      CvUDChgKFggCGgYI3Lu4hQYiCmFsbGNoYW5uZWwS2AMK1QMKCmFsbGNoYW5uZWwSVBJCCgtBcHBs
      aWNhdGlvbhIzEhMKD21hbnVmYWN0dXJlck1TUBIAEgwKCGJ1eWVyTVNQEgASDgoKY2Fycmllck1T
      UBIAGg4KCkNvbnNvcnRpdW0SABrwAhLEAgoLQXBwbGljYXRpb24StAIIARITCg9tYW51ZmFjdHVy
      ZXJNU1ASABIMCghidXllck1TUBIAEg4KCmNhcnJpZXJNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIK
      CggKBFYyXzASABoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zIiIK
      BkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiwKC0VuZG9yc2VtZW50Eh0SEwgDEg8K
      C0VuZG9yc2VtZW50EAIaBkFkbWlucyI1ChRMaWZlY3ljbGVFbmRvcnNlbWVudBIdEhMIAxIPCgtF
      bmRvcnNlbWVudBACGgZBZG1pbnMiIgoHUmVhZGVycxIXEg0IAxIJCgdSZWFkZXJzGgZBZG1pbnMq
      BkFkbWlucxonCgpDb25zb3J0aXVtEhkSFwoVU3VwcGx5Q2hhaW5Db25zb3J0aXVt