info:
      Orderer: Kafka
      Version: 2.2.0
      Distribution: Single Host
      StateDB: CouchDB
      Size: 3 Orgs
    organizations:
    - identities:
        certificates:
        - admin: true
          clientPrivateKey:
            path: secret/carrier/tls/admin.pem
          clientSignedCert:
            path: secret/carrier/tls/admin.cert
          name: "admin"
      connectionProfile:
        path: "./carrierConnectionProfile.yaml"
        discover: True
      mspid: carrierMSP
    - identities:
        certificates:
        - admin: true
          clientPrivateKey:
            path: secret/buyer/tls/admin.pem
          clientSignedCert:
            path: secret/buyer/tls/admin.cert
          name: "admin"
      connectionProfile:
        path: "./buyerConnectionProfile.yaml"
        discover: True
      mspid: buyerMSP
    name: Fabric
    caliper:
      sutOptions:
        mutualTls: false
      blockchain: fabric
      fabric:
        gateway:
          usegateway: true
          discovery: true
    channels:
    - contracts:
      - initArguments: []
        created: true
        instantiate:
          initFunction: init
        install:
          path: simpleauction/
          version: "v1"
          language: golang
        endorsementPolicy:
          policy:
            2-of:
            - signed-by: 0
            - signed-by: 1
          identities:
          - role:
              name: member
              mspId: carrierMSP
          - role:
              name: member
              mspId: buyerMSP
        id: simpleauction
        contractID: simpleauction
      create:
        buildTransaction:
          version: 0
          consortium: "SupplyChainConsortium"
          capabilities: []
          msps: ["carrierMSP", "buyerMSP"]
      channelName: allchannel
    version: "2.0.0"
